In [4]:
import numpy as np
import dask.array as da
from dask.distributed import Client, progress

In [2]:
client = Client(processes=False, threads_per_worker=4, n_workers=1, memory_limit='2GB')
client

/home/artem/Study/KCL/ST50 Project/code/.venv/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 44125 instead
  warnings.warn(


<Client: 'inproc://192.168.1.103/166913/1' processes=1 threads=4, memory=1.86 GiB>

In [24]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.apply_along_axis(np.sum, 1, x)

array([ 6, 15, 24])

In [29]:
dx = da.from_array(x, chunks=(1, 3))
dx

dask.array<array, shape=(3, 3), dtype=int64, chunksize=(1, 3), chunktype=numpy.ndarray>

In [30]:
np.apply_along_axis(np.sum, 1, dx).compute()

array([ 6, 15, 24])

In [57]:
dx.map_blocks(np.sum, chunks=(1,), drop_axis=[1], dtype='float').compute()

array([ 6, 15, 24])